# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SelectorTest
                                 A QGIS plugin
 Selector
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-03
        copyright            : (C) 2025 by Selector
        email                : Selector@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

from pathlib import Path
import sys

for path in Path(__file__).parent.glob("extern/site-packages"):
    sys.path.insert(0, str(path.absolute()))


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SelectorTest class from file SelectorTest.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .selector import SelectorTest
    return SelectorTest(iface)
